language: en
pipeline:
- name: SpacyNLP
  model: en
- name: SpacyTokenizer
- name: SpacyEntityExtractor
- name: SpacyFeaturizer
  pooling: mean
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
policies:
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: MemoizationPolicy
- name: RulePolicy
